managarm/bootstrap-managarm

scripts/grub.cfg, scripts/mkimage
=> Update eir filenames for managarm#103

bootstrap.yml
=> lua: Install to /usr

bootstrap.yml
It compiles but needs some work, for example openat needs to be implemented for archive creation and getpwnam needs to be implemented for extraction.
=> Added a tar port

bootstrap.yml
One small edit to mlibc is needed, gzip really wants fchmod() which I stubbed out.
Also crashes tar when trying to create or unpack a .tar.gz file.
=> Added gzip port.

bootstrap.yml, patches/runit/0001-runit.c-add-sys-select.h-include.patch
this patch is to be included until upstream picks up on it in the mailing list
=> runit: add sys/select.h patch

bootstrap.yml
The `gawk` port works fine in my limited testing, but the `xz-utils` port needs some work in mlibc, the current issue for `xz-utils` is an unknown `printf()` terminator, see the issue [here](https://github.com/managarm/mlibc/issues/57) for more information on that.
=> Added a working port of gawk and a port of xz-utils.

bootstrap.yml, patches/python/0001-Added-managarm-target.patch
This requires https://github.com/managarm/mlibc/pull/73 to be merged in order to build and run.
=> Updated the python port to 3.8.2 and made it work.

bootstrap.yml, patches/glib/0001-Various-fixes-for-managarm-support.patch, patches/pcre/0001-Add-managarm-target.patch
Massive thanks to @no92 for the initial work made to port this!
This PR adds a pcre and glib port, it requires [this](https://github.com/managarm/mlibc/pull/75) PR to be merged in mlibc to build
=> Added a pcre and a glib port.

README.md, bootstrap.yml, docker/Dockerfile, patches/gcc/0002-Managarm-target.patch
This PR adds the following ports
- `gmp`
- `mpfr`
- `mpc`
And fixes the following port
- `gcc`
=> Added some ports

bootstrap.d/dev-perl.yml, bootstrap.d/sys-libs.yml, bootstrap.yml, extrafiles/group, extrafiles/passwd, patches/glib/0001-Various-fixes-for-managarm-support.patch, patches/perl-cross/0001-Add-Managarm-support.patch
This PR adds an `/etc/passwd` and an `/etc/group` file, which bash uses to populate the prompt with an username
=> Add support files and port perl

bootstrap.d/dev-libs.yml
Blocked on a new xbstrap release
=> Updated pcre

bootstrap.d/dev-libs.yml, bootstrap.yml, patches/weston/0002-Add-xwayland-support-for-managarm.patch
This PR adds the following
- A new patch for weston that adds support for xwayland
Furthermore, the following has been updated
- Moved weston to it's proper location and sorted dev-libs.yml alphabetically
Part of #42
=> Updated weston

bootstrap.d/dev-libs.yml, bootstrap.d/x11-libs.yml, patches/libxml/0001-Various-security-fixes.patch
This PR updates the following packages:
- `libX11`, updated from version 1.6.9 to 1.7.0, contains several security fixes.
- `libxkbcommon`, updated from version 1.0.1 to 1.0.2.
- `libxml`, patch various security vulnerabilities.
=> Various updates

bootstrap.d/dev-libs.yml, bootstrap.d/x11-libs.yml, bootstrap.yml, patches/libdrm/0001-Managarm-specific-changes.patch, patches/libdrm/0002-Add-more-managarm-specific-changes.patch, patches/libdrm/0003-Even-more-managarm-specific-changes.patch, patches/libevdev/0001-Add-stddef.h-for-missing-size_t.patch
All of these seem to work properly in QEMU.
=> Version bumps to various wayland-related packages

bootstrap.d/dev-libs.yml, patches/libotf/0001-use-pkg-config-not-freetype-config.patch, patches/libotf/0002-Dont-build-examples.patch
Ported libotf to managarm.
Had some issues, so might have pushed a few times.
=> Add a port of libotf

scripts/run-qemu
To complement https://github.com/managarm/managarm/pull/264.
=> scripts: Add AHCI

bootstrap.d/sys-apps.yml
Requires managarm/managarm#316.
=> ports: Add neofetch

docker/Dockerfile
This PR revamps the dockerfile, removing unneeded packages and adding comments explaining why we install the other packages. It also removes xbps from the docker container as it is not used.
=> docker: Revamp the dockerfile

bootstrap.yml
Had to lose the comments as it's not very easy to incorporate them with the line wrapping.
=> bootstrap.yml: only pass -g to image_create for guestfs

.github/workflows/container.yml, bootstrap.yml, patches/xbps/0002-Add-the-Managarm-amd64-repository-and-remove-the-Voi.patch
=> Update URLs post migration

scripts/meson-kernel-aarch64-managarm.cross-file, scripts/meson-kernel-riscv64-managarm.cross-file
this option is for [properties] rather than [built-in options]
=> scripts/[risc]: move needs_exe_wrapper

bootstrap.yml
This is related to managarm/libasync#12.
=> boostrap.yml: update libasync build recipe

scripts/vm-util.py
A small change that looks nice and doesn't interfere with anything else, should be good to merge.
=> scripts: Make the qemu title bar reflect which Managarm we're running

bootstrap.d/x11-libs.yml
This PR adds several X.Org libraries listed in the BLFS page for X libraries.
=> Add several missing X.Org libraries

patches/rust-libc/0003-managarm-alacritty-updates.patch
=> rust: use core::unimplemented in libc

bootstrap.d/app-arch.yml, bootstrap.d/dev-db.yml, bootstrap.d/dev-lang.yml, bootstrap.d/dev-libs.yml, bootstrap.d/dev-util.yml, bootstrap.d/games-board.yml, bootstrap.d/games-fps.yml, bootstrap.d/games-misc.yml, bootstrap.d/media-fonts.yml, bootstrap.d/media-libs.yml, bootstrap.d/net-libs.yml, bootstrap.d/net-misc.yml, bootstrap.d/sys-apps.yml, bootstrap.d/sys-libs.yml, bootstrap.d/www-client.yml, bootstrap.d/x11-libs.yml, bootstrap.yml
Blocked on managarm/xbstrap#63
=> Add checksums to url type sources

scripts/meson-clang-aarch64-managarm.cross-file, scripts/meson-clang-x86_64-managarm.cross-file
This needs to be merged concurrently with managarm/cxxshim#10 and managarm/managarm#465.
=> Switch from `<experimental/coroutine>` to `<coroutine>`

bootstrap.d/sys-process.yml, bootstrap.yml, patches/htop/0001-Add-Managarm-support-and-patch-out-stuff-we-don-t-su.patch
This PR adds a port of `htop`. For functionality I'm blocked on managarm/managarm#492, but it should build without issues already.
=> htop: Add port

bootstrap.d/dev-libs.yml, bootstrap.d/gui-apps.yml, bootstrap.d/gui-libs.yml, bootstrap.d/gui-wm.yml, bootstrap.d/sys-apps.yml, bootstrap.d/x11-libs.yml, bootstrap.yml, extrafiles/sway-config, patches/sway/0001-Add-managarm-specific-changes.patch, scripts/grub.cfg, scripts/limine.cfg
Blocked on managarm/managarm#449, managarm/managarm#419 and managarm/mlibc#367.
swaybar is known not to work yet.
=> Add Sway port

scripts/update-image.py
See managarm/managarm#520 for the sister PR.
=> scripts: change the root partition GUID to not collide with Windows

bootstrap.d/sys-apps.yml, bootstrap.d/sys-kernel.yml, patches/iproute2/0001-Add-managarm-support.patch, patches/iproute2/0002-ip-fix-the-implicit-assumption-of-AF_UNSPEC-0.patch
Hard-blocked on managarm/managarm#510 and possibly on future PRs.
=> iproute2: add port

bootstrap.d/x11-base.yml, bootstrap.d/x11-libs.yml, bootstrap.d/x11-misc.yml, bootstrap.d/x11-themes.yml, bootstrap.yml, patches/cairo/0001-Patch-out-broken-check.patch, patches/xorg-proto/0001-Add-managarm-support.patch, patches/xorg-server/0001-Add-managarm-support.patch, patches/xwayland/0001-Add-managarm-specific-changes.patch
These updates seem to fix X11 for me.
=> x11-*: update various packages

bootstrap.d/app-misc.yml, bootstrap.d/net-misc.yml, bootstrap.d/sys-libs.yml
This includes `iana-etc`, `tzdata` and `pciids`.
=> Update several packages that just provide files to read data from

scripts/grub.cfg, scripts/update-image.py
=> grub: search for root instead of hard-coding (hd0,gpt2)

bootstrap.d/games-misc.yml
Sorry that this happened! Looks like I somehow managed to not change this checksum when I was creating this recipe
=> openttd-openmsx: fix checksum

.github/workflows/fixups.yml
We have it for mlibc, I want it for bootstrap too.
=> ci: add fixup checker

bootstrap.d/media-libs.yml
=> Update the gstreamer stack

bootstrap.d/app-accessibility.yml, bootstrap.d/dev-libs.yml, bootstrap.yml, docker/Dockerfile, patches/gobject-introspection/0002-Add-support-for-GI_LDD_WRAPPER-environment-variable.patch, scripts/ldd-wrapper, scripts/meson-x86_64-managarm-goi.cross-file, scripts/run-wrapper
Blocked on managarm/mlibc#967, managarm/mlibc#968, managarm/mlibc#969, managarm/xbstrap#78
=> Work towards gobject-introspection support

bootstrap.yml
=> gcc: Update to 13.2.2

bootstrap.d/dev-qt.yml, patches/qt6/0001-Switch-to-a-patched-qtbase-repo.patch, patches/qtbase6/0001-Add-Managarm-support.patch
Also fixes a broken patch for qtbase6.
=> Qt6: Update to Qt 6.6.2

bootstrap.yml
Latest master has a bunch of improvements and correctness touch-ups for dynamic table loads, error logging, as well as a few bug fixes.
=> uacpi: bump to latest master

bootstrap.d/app-misc.yml
Depends on managarm/mlibc#1071.
=> tmux: add port

bootstrap.d/dev-libs.yml, bootstrap.d/net-wireless.yml, bootstrap.yml, patches/iw/0001-Add-Managarm-support.patch
This PR adds `libnl`, to interface with netlink, and `iw`, to set wireless items.
=> Add two ports related to wireless communication

scripts/vm-util.py
Device aliases for some supported USB devices are provided for convenience. The `--usb-passthrough-pcap` option records a pcap file, which is named like the input to the option.
=> scripts/vm-util: support USB passthrough with pcap capture and aliases

bootstrap.d/app-crypt.yml, bootstrap.d/dev-libs.yml, bootstrap.d/dev-qt.yml, bootstrap.d/kde-frameworks.yml, bootstrap.d/media-libs.yml, bootstrap.d/net-irc.yml, patches/breeze-icons/0001-Install-qrcAlias-to-enable-cross-compilation.patch, patches/kcoreaddons/0001-Add-Managarm-support.patch, patches/kio/0001-Add-Managarm-support.patch, patches/libcanberra/libcanberra-0.30-wayland-1.patch
=> Add a port of konversation

bootstrap.d/managarm-libc.y4.yml, bootstrap.d/managarm-libs.y4.yml, bootstrap.d/managarm-system.y4.yml, bootstrap.d/managarm-tools.y4.yml, bootstrap.d/tasks.y4.yml, bootstrap.yml, scripts/limine.conf, scripts/meson-kernel-uefi-x86_64-managarm.cross-file, scripts/update-image.py, scripts/vm-util.py
Depends on managarm/managarm#730.
=> `eir-uefi` enablement

bootstrap.d/managarm-tools.y4.yml, bootstrap.d/tasks.y4.yml, scripts/update-image.py
Requires a new xbstrap release
=> Fix {re,}make-image tasks producing broken BIOS images

bootstrap.d/managarm-tools.y4.yml, patches/ovmf/0001-Disable-OVMF-output-over-serial.patch, scripts/grub.cfg, scripts/limine.conf, scripts/update-image.py, scripts/vm-util.py
Counterpart to managarm/managarm#734.
=> Provide thor via initrd, drop multiboot1

scripts/vm-util.py
This allows for specifying how devices should be laid out in a YAML file. Currently, this implementation only supports PCI bridges and (multifunction) PCI devices, but can be extended to other devices if needed.
Example spec file:
```yaml
- name: nvidia-bridge
type: pci-bridge
devices:
- name: nvidia-passthrough
type: pci-multifunction-device
functions:
- host: "01:00.0"
- host: "01:00.1"
- host: "01:00.2"
- host: "01:00.3"
- name: i226-V
type: pci-device
host: "04:00.0"
```
This passes through the multifunction device from the host at segment 0, bus 1, device 0, functions 0 through 3 to the guest, placing them behind a PCI bridge under one device. The PCI device is passed through and most likely placed on bus 0 by qemu.
=> scripts/vm-util: add `--device-spec` option

scripts/limine.conf, scripts/update-image.py
This PR adds an eir that uses the Limine protocol to boot.
Also refactors the Limine config file.
=> update-image: Add limine boot

bootstrap.d/app-shells.y4.yml, bootstrap.d/dev-libs.y4.yml, bootstrap.d/www-client.y4.yml, patches/libevent/0001-Add-missing-include-and-fix-wrong-shebang.patch, patches/zsh/0001-Add-missing-include.patch
=> More xbbs fixes

bootstrap.d/app-accessibility.y4.yml, bootstrap.d/app-crypt.y4.yml, bootstrap.d/dev-lang.y4.yml, bootstrap.d/dev-libs.y4.yml, bootstrap.d/dev-util.y4.yml, bootstrap.d/gui-apps.y4.yml, bootstrap.d/media-libs.y4.yml, bootstrap.d/net-irc.y4.yml, bootstrap.d/net-print.y4.yml, bootstrap.d/x11-apps.y4.yml, bootstrap.d/x11-libs.y4.yml, patches/cups/0001-Add-missing-includes.patch, patches/weston/0001-Managarm-specific-changes.patch
=> Xbbs fixes

scripts/vm-util.py
This assumes that the user spins up their own TFTP root and NVMe-over-fabrics controller, and thus could use more automation, but this is a simple start.
=> scripts/vm-util: add support for basic NVMe-over-fabrics

bootstrap.d/app-misc.y4.yml, bootstrap.d/dev-libs.y4.yml, patches/fastfetch/0001-Add-Managarm-support.patch
Blocked on managarm/mlibc#1216
=> Add a port of fastfetch

bootstrap.d/dev-libs.y4.yml
This is a potential multi lib issue but we can work around it for now.
=> icu: Work around build failure on RISC-V

bootstrap.d/managarm-system.y4.yml
Depends on https://github.com/managarm/managarm/pull/868
=> managarm: Build testsuite on Linux and on Managarm

bootstrap.d/dev-libs.y4.yml, patches/weston/0001-Managarm-specific-changes.patch, patches/weston/0002-Add-systemd-unit-files.patch
This PR enables systemd support on Weston.
Part of the systemd on Managarm project.
=> weston: Enable systemd support

bootstrap.d/dev-util.y4.yml
Add `pc` port - The venerable portable programmer's calculator
=> pc: add port

bootstrap.d/app-editors.y4.yml
=> OpenVi: Add port

bootstrap.d/managarm-system.y4.yml, scripts/meson-kernel-uefi-aarch64-managarm.cross-file, scripts/update-image.py, scripts/vm-util.py
Depends on managarm/managarm#931
=> Build managarm-kernel-uefi for aarch64

bootstrap.d/app-emulation.y4.yml, patches/qemu/0001-configure-add-managarm-support.patch, patches/qemu/0002-dmalog-Add-device.patch, patches/qemu/0003-Add-managarm-support.patch, patches/qemu/0004-smbios-zero-terminate-strings-read-from-files.patch, patches/qemu/0005-smbios-remove-unnecessary-snprintf.patch, patches/qemu/0006-Add-IRQ-tracepoint-for-serial.patch, scripts/update-image.py, scripts/vm-util.py
Accumulated fixes and improvements while porting nvidia-open.
=> scripts: misc improvements

bootstrap.d/tasks.y4.yml
Circularly depends on https://github.com/managarm/managarm/pull/970.
=> update-initrd: Pass --sysroot

bootstrap.d/managarm-libs.y4.yml, bootstrap.d/managarm-system.y4.yml, patches/freebsd-e1000/0001-meta-add-meson.build.patch
Circular dependency on managarm/managarm#991.
=> freebsd-e1000: build static library for managarm-system

bootstrap.d/dev-lang.y4.yml, bootstrap.d/dev-libs.y4.yml, bootstrap.d/gnome-extra.y4.yml, bootstrap.d/gui-libs.y4.yml, bootstrap.d/media-libs.y4.yml, bootstrap.d/net-libs.y4.yml, patches/gtk4/0001-Add-Managarm-support.patch
Thanks to @48cf for the help with finding the issue!
=> Fix introspection issues and enable GTK4 and gnome-calculator

bootstrap.d/app-crypt.y4.yml, bootstrap.d/app-misc.y4.yml, bootstrap.d/dev-libs.y4.yml, bootstrap.d/media-libs.y4.yml, bootstrap.d/net-misc.y4.yml, bootstrap.d/sys-apps.y4.yml, bootstrap.d/x11-apps.y4.yml
Also gains a drive-by fix to xclock installing files in the wrong location.
=> meta: Fix several packages that did not keep empty directories

bootstrap.d/managarm-system.y4.yml, scripts/meson-kernel-uefi-aarch64-managarm.cross-file, scripts/meson-kernel-uefi-riscv64-managarm.cross-file, scripts/meson-kernel-uefi-x86_64-managarm.cross-file, scripts/vm-util.py
This will enable us to use uACPI in eir.
=> Update uACPI and pass ffreestanding to UEFI builds

bootstrap.d/managarm-libs.y4.yml, bootstrap.d/managarm-system.y4.yml
Depends on managarm/libarch#11 and managarm/managarm#1009.
=> libarch: install as package

bootstrap.d/managarm-libc.y4.yml, bootstrap.d/net-libs.y4.yml, patches/webkitgtk/0001-Initial-Managarm-support.patch
This seems to unbreak MiniBrowser.
=> WebKit update
