managarm/bootstrap-managarm

bootstrap.yml
Cairo compilation fails on my system, complaining about double redefinitions in my X11 system headers. Passing `--disable-xlib` fixes the issue, makes cairo compile, and testing weston does not reveal any glaring issues with this.
=> Make cairo compilable on systems with X11 headers present

ci/Jenkinsfile, docker/Dockerfile
Possible defect: the two rsync steps towards the end could make the builds fail on computers of developers not set up right. This is a problem only for those who wish to maintain CI
=> Start CI migration to Jenkins pipelines

bootstrap.yml
This pull request adds the following ports.
- `libpipeline`, this being a direct dependency to `man-db`. This seems to work fine.
- `gdbm`, again, being a direct dependency to `man-db`, as `man-db` needs a database. Should work fine with the changes I proposed in mlibc.
- `man-db`, this port is incomplete at the moment, as calling `man man` crashes with a call to `towlower()`, which is currently unimplemented.
=> Added a port of man-db and required dependencies

bootstrap.yml
- `tar`, works fine as is, but when working with gzip compressed archives errors
- `gzip`, works fine on it's own
- `grep`, works fine on small directories, running it on, for example, `/usr/include` will eventually OOM
- `diffutils`, cmp and diff work fine, sdiff is untested and diff3 is broken
- `less`, works fine as is
- `file`, works fine on executables, missing `regcomp()` on text files.
=> Enabled the following ports by default as they are (mostly) working.

bootstrap.yml
This PR fixes python's build system when python 3.8 is not available on the host and adds the following ports.
- `desktop-file-utils`, a runtime dependency of `glib`
- `which`
=> Fix for python's build system and new ports

README.md, docker/Dockerfile
This should allow host-python to build and adds some dependencies for future use.
=> Updated required dependencies for a host build

bootstrap.yml, patches/libressl/0001-Various-fixes-for-managarm-support.patch, scripts/prepare-sysroot
This PR adds the following new ports
- `pkg-config`, still needs some libc work in regards to ungetc at the moment
- `libxml2`, works, some programs require `pthread_equal` and the `python3` module doesn't install
- `itstool`, has some issues, build time dep for `shared-mime-info`
- `shared-mime-info`, wants `pthread_equal`
Furthermore, the following ports received updates
- `libressl`, fixup on the port and added a patch
- `python` and `grep`, updated dependencies
A few ports have been enabled by default, these are: `pcre`, `glib`, `file`, `desktop-file-utils`, `libxml2` and `libressl`
Lastly an update to `scripts/prepare-sysroot` to satisfy a dependency on `/bin/sh` is included in this PR
=> Various ports and fixes

bootstrap.yml, scripts/mkimage, scripts/prepare-sysroot
- `gettext`
- `findutils`
- `bzip2`
Furthermore, it adds a compatibility symlink from `gcc` to `cc`, so build systems that call `cc` can work.
=> Added various ports

bootstrap.d/app-admin.yml, bootstrap.d/sys-devel.yml, bootstrap.yml, extrafiles/syslog.conf, patches/make/0001-Fix-for-Managarm-support.patch, patches/sysklogd/0001-Add-managarm-support.patch
This PR adds the following two ports:
- `sysklogd`, compiles fine, but complains about `gethostbyname()` on runtime
- `make`, compiles and runs fine, possible issue with binutils `as` on `gcc` invocation from a makefile
=> Add sysklogd and make ports

bootstrap.d/net-misc.yml, bootstrap.d/sys-devel.yml, bootstrap.d/sys-libs.yml, bootstrap.yml, patches/ncurses/0001-Add-managarm-support.patch
- `wget`, seems to work with direct ip's, barring improvements to the experimental tcp implementation, doesn't correctly work with hostnames.
- `curl`, builds, when given an ip or hostname, dies on `inet_pton`
- `patch`, should work out of the box
Furthermore, the following port has been updated
- `ncurses`, the source is now a git repo, and with a nice little patch `ncurses` is now able to produce shared libraries, satisfying various other packages, notably the `curses` module of `python`
This PR is part of #33
=> Add ports of wget, curl and patch; fix ncurses

bootstrap.yml, scripts/mkimage, scripts/prepare-sysroot
This PR makes `/bin`, `/lib` and `/sbin` symlinks to their counterparts in `/usr`
After merging of this PR, existing build environments should do the following to be sure:
- Either mount the image, and remove the `/bin` and `/lib` folders, or remove the image completely and generate a new one,
- Remove the `/bin` and `/lib` folders from the `system-root` directory,
- Run the `prepare-sysroot` script,
- Run `xbstrap install --all` to get the symlinks and needed configuration files,
- Update the image as usual.
After performing the above steps once, they shouldn't be needed any longer, and regular image updating can be resumed.
This PR is blocked on a new xbstrap release ~~which includes managarm/xbstrap#22 and managarm/xbstrap#23~~(both merged)
=> Made /bin and friends symlinks to their /usr counterparts

bootstrap.d/app-arch.yml, bootstrap.d/dev-db.yml, bootstrap.d/dev-lang.yml, bootstrap.d/sys-devel.yml, bootstrap.d/x11-base.yml, bootstrap.d/x11-libs.yml, bootstrap.d/x11-misc.yml, bootstrap.yml, patches/xorg-proto/0001-Add-managarm-support.patch
The following ports are added:
- A bunch of xorg ports, see the relevant commit for details
- `bison`, untested but prints help message when invoked
- `flex`, broken, needs `regcomp()` for even `flex --help` to work (issue managarm/mlibc#98)
- `sqlite`, seems to work
- `yasm`, untested
Furthermore, the following ports received updates
- `bzip2`, fix symlink installation and enable by default
- `nasm`, moved to a tarball to allow compilation and enable by default
- meta: A couple of files have been reordered so that the packages are sorted alphabetically.
This pr is part of #33
=> Various ports and updates

bootstrap.d/x11-apps.yml, bootstrap.d/x11-base.yml, bootstrap.d/x11-libs.yml
This PR adds the following xorg applications and their depending libraries.
- `libXt`, the X Toolkit Library.
- `libSM`, the X Session Management Library.
- `libICE`, the X Inter Client Exchange Library.
- `libXtst`, the Xlib-based library for XTEST & RECORD extensions.
- `libXmu`, the X interface library for miscellaneous utilities not part of the Xlib standard.
- `xdpyinfo`, a display information utility for X.
- `xdriinfo`, queries configuration information of DRI drivers.
- `xkill`, kills a client by its X resource.
- `xlsclients`, lists client applications running on a display.
- `xwininfo`, a window information utility for X.
=> Add several xorg applications

bootstrap.d/media-libs.yml, bootstrap.d/x11-apps.yml, patches/mesa-demos/0001-Disable-GLEW-check.patch
This PR adds a basic port of `mesa-progs`, which includes the GLX only version of `glxgears`.
Not all features are enabled to work around the `GLEW` requirement, which we don't have because it has a shitty build system.
The following ports have been added, and enabled by default.
- `GLU`, the Mesa OpenGL Utility Library, a required dependency for `mesa-progs`.
- `mesa-progs`, a collection of demos and tests for mesa, includes the famous `glxgears` program.
This PR is blocked on managarm/mlibc#143
As this PR satisfies the last requirement of #42, this PR closes #42
=> ports: Add glxgears and friends

bootstrap.d/dev-libs.yml, bootstrap.d/games-board.yml, bootstrap.d/games-misc.yml, bootstrap.d/media-libs.yml, bootstrap.d/x11-apps.yml, bootstrap.d/x11-libs.yml, bootstrap.yml, patches/ace/ace-1.4-libpng15.patch, patches/libxaw/0001-Specific-managarm-changes.patch, patches/nyancat/0001-Add-managarm-support.patch
This PR adds the following new ports:
- `ace`, `ace` is a collection of card games, like solitaire, built upon the X libraries. This port is enabled by default.
- `freeglut`, `freeglut` is a 100% open sourced clone of the GLUT library. This port is used by `mesa-progs` and enabled by default.
- `icu`, provides unicode support to applications.
- `libXaw`, a dependency for `xclock`, enabled by default.
- `libXpm`, a dependency for `libXaw`, enabled by default.
- `nyancat`, the classic nyancat as used in debian. Written by klange and enabled by default.
- `xclock`, a small graphical clock, enabled by default.
Furthermore, the following ports received updates:
- `libICE`, enabled by default.
- `libSM`, enabled by default.
- `libXmu`, enabled by default.
- `libXt`, enabled by default.
- …
=> Add various new ports and enable some stable ports

bootstrap.d/app-admin.yml, bootstrap.d/app-arch.yml, bootstrap.d/app-editors.yml, bootstrap.d/app-misc.yml, bootstrap.d/app-shells.yml, bootstrap.d/dev-db.yml, bootstrap.d/dev-lang.yml, bootstrap.d/dev-libs.yml, bootstrap.d/dev-util.yml, bootstrap.d/games-board.yml, bootstrap.d/games-misc.yml, bootstrap.d/media-fonts.yml, bootstrap.d/media-libs.yml, bootstrap.d/net-misc.yml, bootstrap.d/sys-apps.yml, bootstrap.d/sys-devel.yml, bootstrap.d/sys-libs.yml, bootstrap.d/x11-apps.yml, bootstrap.d/x11-base.yml, bootstrap.d/x11-libs.yml, bootstrap.d/x11-misc.yml, bootstrap.yml
This PR adds versioning information for use in packaging where it was known, e.g. everything that is not built directly from master (with a few small exceptions).
=> Add version info to nearly all packages

bootstrap.d/app-arch.yml, bootstrap.d/dev-lang.yml, bootstrap.d/dev-util.yml, bootstrap.d/meta-pkgs.yml, bootstrap.d/net-misc.yml, bootstrap.d/sys-devel.yml, bootstrap.yml
This PR adds a `base` meta package which can be used to boot into kmscon and download more packages with `xbps` pending mlibc support (issues managarm/mlibc#51, managarm/mlibc#168, managarm/mlibc#169 and managarm/mlibc#170).
It also adds a `base-devel` meta package which holds the equivalent of `build-essentials` on debian, e.g essential build tools like gcc, binutils and make. As we are still missing software in the ports collection to fill this properly, I expect this meta package to grow in the future
The following ports are enabled by default:
- `xz-utils`
- `wget`
- `make`
- `m4`
- `patch`
- `pkg-config`
Furthermore, the following port received an update
- `python`, bump revision and depend on `xz-utils`
=> Add several meta packages

bootstrap.d/app-admin.yml, bootstrap.d/app-shells.yml, bootstrap.d/dev-db.yml, bootstrap.d/dev-lang.yml, bootstrap.d/dev-libs.yml, bootstrap.d/dev-util.yml, bootstrap.d/net-misc.yml, bootstrap.d/sys-apps.yml, bootstrap.d/sys-devel.yml, bootstrap.d/sys-libs.yml, bootstrap.d/x11-misc.yml, bootstrap.yml
This PR prepares the repo for the new xbstrap release. It adds `everything_by_default: false` to only build a minimal subset by default (when using `xbstrap`, `xbstrap-pipeline` ignores this), it adds `default: true` to that minimal subset (which can boot `kmscon` with a `bash` shell and some config files, `core-files` for filesystem layout and `iana-etc` for the `/etc/services` and `/etc/protocols` file) and it dropped all the `default: false`, as that is now the default, and added `stability_level: broken` to packages which had `default: false`. I expect to remove this label from some packages in the coming days after I've confirmed that they actually build and do something remotely useful, like not crashing the `posix-subsystem` server on executing their help command.
This PR is …
=> bootstrap.yml: Add stability_level annotations

README.md, bootstrap.d/dev-libs.yml, bootstrap.d/media-gfx.yml, bootstrap.d/media-libs.yml, bootstrap.d/x11-libs.yml, bootstrap.yml, docker/Dockerfile
- `graphite2`, used by harfbuzz for rendering.
- `harfbuzz`, used for rendering fonts and a required dependency of `pango`.
- `fribidi`, used by `pango` for rendering.
- `pango`, used by many gtk based applications for rendering and used by kmscon for freetype font rendering.
Furthermore, this PR updates the Dockerfile and the readme with a new host dependency.
=> Add several font-related ports

bootstrap.d/dev-libs.yml, bootstrap.d/sys-apps.yml, bootstrap.d/sys-libs.yml
This PR updates various packages:
- `glib`, updated from version `2.66.1` to `2.66.2`, fixes a bug in timezone handling with regards to daylight saving time
- `icu`, updated from version `67.1` to `68.1`
- `less`, updated from version `553` to `561`
- `mpc`, updated from version `1.1.0` to `1.2.1`, also updated the source url
- `mpfr`, updated from version `4.0.2` to `4.1.0`
- `tzdata`, updated from version `2020a` to `2020d`
=> Various updates

bootstrap.d/dev-libs.yml, bootstrap.d/dev-util.yml, bootstrap.yml, patches/libuv/0001-Add-Managarm-support.patch
- `libuv`, a direct dependency of `cmake`,
- `cmake`, the successor to the old-school configure scripts.
This PR is part of #33 
This PR is blocked on #53 
This PR is blocked on managarm/xbstrap#24
This PR is blocked on a new xbstrap release
This PR is blocked on managarm/mlibc#158
This PR is blocked on managarm/mlibc#159
This PR is blocked on managarm/mlibc#163
This PR is blocked on managarm/mlibc#164
This PR is blocked on a new mlibc release
=> Add a cmake and libuv port

bootstrap.d/meta-pkgs.yml, bootstrap.yml, ci/pipeline.yml
This PR fixes the image generation for the ci and updates the `base-devel` meta package with `bc` and `cmake` now that those are available. Furthermore, a new meta package called `gui` is added, which depends on `base`, `weston` and some X based utility programs.
=> Fix for ci image generation and some updates

bootstrap.d/app-arch.yml, bootstrap.d/app-editors.yml, bootstrap.d/dev-libs.yml, bootstrap.d/media-libs.yml, bootstrap.d/sys-apps.yml, bootstrap.yml, patches/libiconv/0001-Remove-calls-to-versioned-binaries.patch
This PR adds the following new ports:
- `libiconv`, as mlibc doesn't properly implement the `iconv()` functions we use this utility library to provide those.
- `man-pages-posix`, a collection of man pages in the sections `0p`, `1p` and `3p`, mostly related to posix functions.
Furthermore, the following ports were updated:
- `libtool`, updated version from 2.4.5 to 2.4.6.
- `man-db`, add a dependency on `libiconv`, bump revision and fix the install location to use the correct version.
- `libarchive`, bump revision and add a dependency on `libressl`, `zlib`, `xz-utils`, `libiconv`, `libexpat` and `libxml`
- `vim`, bump revision and add a dependency on `libiconv`.
- `glib`, bump revision and add a dependency on `zlib`.
- `fontconfig`, bump revision and add a dependency on `libiconv`.
- …
=> libiconv port and various updates

bootstrap.d/app-arch.yml
This PR adds the following port:
- `zstd`, required by `xbps` to read the repo.
The following packages received updates:
- `libarchive`, depend on `zstd`.
=> Add a port of zstd

patches/libinput/0001-Add-managarm-specific-changes.patch
This will now use managarm's linux/input.h instead of the in-tree Linux copy, which feels like an ugly hack.
Depends on managarm/mlibc#218
=> Add patch for libinput to fix build errors

bootstrap.d/app-editors.yml, bootstrap.d/dev-libs.yml, bootstrap.yml
This PR adds a port of `libintl` and makes some adjustments to several packages to reflect this. In addition, it disabled building the intl option in mlibc.
This PR adds the following port:
- `libintl` as provided by gettext for internationalization.
Furthermore, the following ports received updates:
- `mlibc` and `mlibc-headers` now disable building the `intl` option,
- `glib`, depend on `libintl` and bump revision,
- `nano`, depend on `libintl` and bump revision.
Blocked on managarm/mlibc#223
=> sys-libs: Add a port of libintl

bootstrap.d/dev-libs.yml, bootstrap.d/dev-util.yml, bootstrap.d/games-misc.yml, bootstrap.d/media-libs.yml, bootstrap.d/x11-libs.yml, bootstrap.d/x11-misc.yml
This PR adds a port of `gtk+-2` and dependencies, and adds a demo of a game of life written for `gtk`
The following ports have been added:
- `libjpeg-turbo`, add port, dependency of `gdk-pixbuf`,
- `gdk-pixbuf`, add port, core dependency of `gtk`,
- `atk`, add port, used to provide accessibility functions to `gtk`,
- `gtk+-2`, add port, version 2 of the GIMP ToolKit, used throughout GNOME and various other applications for GUI related functionality,
- `gtklife`, add port, a rewrite of the classic game of life for gtk.
Furthermore, the following ports received updates:
- `itstool`, promote to stable as it is needed for `gdk-pixbuf`,
- `shared-mime-info`, promote to stable as it is needed for `gdk-pixbuf`.
=> Add GTK+-2 and friends

README.md
libssl-dev doesnt come default on ubuntu (tested on lubuntu 20.04).
WIthout it -lnetwork wont link against openssl.
(it just lists libssl-dev as a dependency now in the README)
=> on debian based systems libssl-dev is required as dependency

bootstrap.d/dev-libs.yml, bootstrap.d/media-libs.yml, bootstrap.d/x11-libs.yml
This fixes several build failures introduced by pr #69
=> atk, gdk-pixbuf, libjpeg-turbo: Use the arch suffixed cross files

bootstrap.d/app-arch.yml, bootstrap.d/dev-libs.yml, bootstrap.d/media-libs.yml, bootstrap.d/net-misc.yml, bootstrap.d/x11-libs.yml, patches/d0-blind-id/0001-Add-managarm-support.patch, patches/libmodplug/0001-Add-managarm-support.patch, patches/libtheora/0001-Remove-the-force-configure-from-autogen.sh.patch, patches/popt/0001-Fix-missing-termios-include.patch
This PR adds the following new ports:
- `libogg`,
- `libvorbis`,
- `libtheora`,
- `libmodplug`,
- `d0-blind-id`,
- `libxxf86dga`,
- `popt`, a dependency for `rsync`,
- `lz4`, a dependency for `rsync`,
- `xxhash`, a dependency for `rsync`,
- `rsync`.
Part of #33
=> Add a port of several libraries and rsync

bootstrap.d/app-arch.yml, bootstrap.d/app-editors.yml, bootstrap.d/app-shells.yml, bootstrap.d/dev-db.yml, bootstrap.d/dev-libs.yml, bootstrap.d/media-libs.yml, bootstrap.d/net-misc.yml, bootstrap.d/sys-apps.yml, bootstrap.d/sys-libs.yml, bootstrap.d/x11-libs.yml, bootstrap.d/x11-misc.yml, bootstrap.yml, extrafiles/nanorc, extrafiles/root-nanorc, patches/bash/0001-Remove-config.h-from-build-machine-source-files.patch, patches/bash/0002-Add-managarm-to-config.sub.patch, patches/bash/0003-Fix-use-of-SEEK-constants.patch, patches/ncurses/0001-Add-managarm-support.patch, patches/readline/0001-Add-managarm-support.patch, scripts/update-image.py
This PR updates the following packages:
- `glew`, updated from version 2.1.0 to 2.2.0,
- `wget`, updated from version 1.20.3 to 1.21.1,
- `sqlite`, updated from version 3.34.0 to 3.34.1,
- `tar`, updated from version 1.32 to 1.33,
- `findutils`, updated from version 4.7.0 to 4.8.0,
- `tzdata`, updated from version 2020f to 2021a,
- `bash`, install additional files and updated from version 4.4 to 5.1.4,
- `ncurses`, yes, our nanosleep works fine, please use it and updated from version 6.1 to 6.2,
- `nano`, install a nanorc in the users home dir by default and modify the default,
- `vim`, updated from version 8.2.0814 to 8.2.2433,
- `iana-etc`, updated from version 2.30 to 20210202,
- `xorg-util-macros`, updated from version 1.19.1 to 1.19.3,
- `libxt`, updated from version 1.2.0 to 1.2.1, …
=> Updates of various packages

bootstrap.d/app-arch.yml, bootstrap.d/dev-lang.yml, bootstrap.d/dev-libs.yml, bootstrap.d/dev-util.yml, bootstrap.d/net-misc.yml, bootstrap.d/sys-apps.yml, bootstrap.yml, patches/openssl/0001-Add-managarm-support.patch
This PR makes the following changes to the ports listed below, all in preparation of removing `libressl`. This decision was made after gentoo announced that they are no longer supporting `libressl` installs because the work required to do so was increasing without the original benefits. We follow them in this decision to lighten the workload.
- `libressl`, deprecate in favor of `openssl`,
- `openssl`, add port,
- `libarchive`, depend on `openssl` instead of `libressl`,
- `python`, depend on `openssl` instead of `libressl` and add a dependency on `util-linux`,
- `cmake`, depend on `openssl` instead of `libressl`,
- `curl`, depend on `openssl` instead of `libressl`,
- `socat`, depend on `openssl` instead of `libressl`,
- `rsync`, depend on `openssl` instead of `libressl`,
- `wget`, depend …
=> Deprecate libressl and add OpenSSL

scripts/update-image.py
This prevents broken images where the `/bin`, `/lib` and `/sbin` symlinks are not correctly present, thus causing a boot failure
=> scripts: Add sanity checking to update-image.py

bootstrap.d/dev-lang.yml, patches/rust-libc/0001-managarm-initial-port.patch, patches/rust/0001-managarm-initial-port.patch
This PR adds patches for Rust's `std` and `libc` crates and allows us to cross-compile basic Rust programs for managarm.
The full install takes ~1h20 on my machine (4 core low spec laptop), as we compile both stage1 and stage2. This may not be strictly necessary, but is a good idea to avoid ABI issues in future (e.g with procedural macros).
Partially addresses managarm/managarm#91.
=> rust: Add cross-compiler port

bootstrap.yml, patches/gcc/0001-Fix-libstdc-in-freestanding-mode.patch, patches/gcc/0002-Managarm-target.patch, scripts/meson-clang-aarch64-managarm.cross-file, scripts/meson-clang-x86_64-managarm.cross-file
This PR upgrades `kernel-gcc`, `system-gcc`, `bootstrap-system-gcc` and `gcc` to version 10.3. This is pending some changes in managarm (managarm/managarm#284) and cxxshim (related to the cstddef and atomic headers).
After this PR, the following _needs_ to be refetched, patched, and build from scratch: `bootstrap-system-gcc`, `kernel-gcc` and `system-gcc`. For good measure, after that, one should make sure that the latest `managarm`, `mlibc` and `cxxshim` are available, and issue a full rebuild (possibly issuing a reconfigure) of `managarm-kernel`, `managarm-system` and `mlibc`.
This PR is blocked on managarm/managarm#284 (only merge this PR if all the other blockers are resolved!)
This PR is blocked on managarm/mlibc#262 (only merge this PR if all the other blockers are resolved!)
This …
=> Upgrade gcc to version 10.3

bootstrap.d/dev-lang.yml, bootstrap.d/sys-apps.yml, bootstrap.d/sys-libs.yml, bootstrap.yml, extrafiles/config.toml, patches/rust-libc/0001-managarm-initial-port.patch, patches/rust-libc/0002-managarm-Add-missing-glue-for-memmap-num_cpus-and-us.patch, patches/rust-num-cpus/0001-managarm-Initial-port.patch, patches/rust-users/0001-managarm-Initial-port.patch, scripts/cargo-inject-patches.py
This PR implements support for `cargo` builds. We also port `ripgrep` and `exa`, implementing the necessary patches for them to build.
In order to test this PR, you must have managarm/xbstrap#48 merged locally, and then run `xbstrap init ../src` from your `build` directory.
=> rust: Port `cargo`, `ripgrep` and `exa`

bootstrap.d/dev-lang.yml, patches/rust/0001-managarm-initial-port.patch, patches/rust/0002-managarm-fix-build-target-in-x.py-and-bootstrap.patch
This PR fixes Rust builds for use with `cbuildrt`.
First, we allow `xbstrap` to set `CARGO_HOME` when building `rustc`. Then, we fix `rustc`'s build system so that it uses the right `--target` for bootstrapping.
=> rust: Fix cargo target selection when setting CARGO_HOME

bootstrap.d/dev-lang.yml, bootstrap.d/sys-apps.yml, bootstrap.d/sys-libs.yml
Requires https://github.com/managarm/xbstrap/pull/49.
This should fix the rust-related CI build failures, finally.
We also move `ripgrep` and `exa` packages to be in alphabetical order.
=> rust: Use rust-patched-libs source group

bootstrap.d/app-crypt.yml, bootstrap.d/app-misc.yml, bootstrap.d/dev-libs.yml, bootstrap.d/meta-pkgs.yml
This PR adds a port of `make-ca`, which is a script that BLFS uses to generate the certificates used by `OpenSSL`. As the package that holds the certificates is often times called `ca-certificates`, I opted to use the same name. This package has also been added to the `base` metapackage and all dependencies of `ca-certificates` and `ca-certificates` itself received a label marking them ready to build on AArch64.
A small note regarding the version number used on `ca-certificates`, as is common with the `ca-certificates` package, at least on Debian based systems, I have chosen to use the date of package creation / update as a version number. This way, it is clear on which day the certificates have been generated.
=> Add certificates

scripts/vm-util.py
This PR adds `disable-modern=on` to the qemu command line. It seems that this argument was missed while converting the old `run-qemu` script to the new `vm-util.py` script.
=> scripts/vm-util: Add disable-modern=on to the qemu command line

bootstrap.d/app-admin.yml, bootstrap.d/app-arch.yml, bootstrap.d/app-crypt.yml, bootstrap.d/app-editors.yml, bootstrap.d/app-misc.yml, bootstrap.d/app-shells.yml, bootstrap.d/dev-db.yml, bootstrap.d/dev-lang.yml, bootstrap.d/dev-libs.yml, bootstrap.d/dev-util.yml, bootstrap.d/games-board.yml, bootstrap.d/games-misc.yml, bootstrap.d/media-fonts.yml, bootstrap.d/media-gfx.yml, bootstrap.d/media-libs.yml, bootstrap.d/meta-pkgs.yml, bootstrap.d/net-misc.yml, bootstrap.d/sys-apps.yml, bootstrap.d/sys-boot.yml, bootstrap.d/sys-devel.yml, bootstrap.d/sys-libs.yml, bootstrap.d/x11-apps.yml, bootstrap.d/x11-base.yml, bootstrap.d/x11-libs.yml, bootstrap.d/x11-misc.yml, bootstrap.yml
This PR removes the implicit package definition from `mlibc` and `mlibc-headers`, and adds a dependency on `mlibc` to all packages that require it.
=> Implicit package removal

bootstrap.d/meta-pkgs.yml, scripts/update-image.py
This PR adds `gcc` to `base` and removes it from `base-devel`. This eliminates the need to copy `libgcc_s.so.1` and `libstdc++.so.6` from `system-gcc` as the `gcc` package provides them. This is an temporarily solution, and should be partially reverted whenever `xbstrap` gains the ability to make multiple packages from one build recipe, in which case `gcc` will be split in at least `gcc`, `libgcc` and `libstdc++`, `gcc` will move back to `base-devel` and both `libgcc` and `libstdc++` will be added as a dependency to `base`.
=> Temporarily add gcc to base as it includes libstdc++ and libgcc

bootstrap.d/dev-lang.yml, bootstrap.d/sys-apps.yml
This PR changes `util-linux` to produce `util-linux-libs`, which contains the libraries and header files that `util-linux` provides, and `util-linux`, which holds binaries and their documentation. The rationale behind this change is allowing `eudev` to be build with `libblkid` support (to be enabled at a later date), which is currently impossible as `util-linux` uses `eudev` itself when building certain programs, creating a circular dependency.
=> util-linux: Split into a library and binaries package

bootstrap.d/meta-pkgs.yml, bootstrap.yml
The meta packages used to have the same source as managarm, this is unneeded and makes versioning hard to do for these packages. The same goes for the `core-files` package. This PR fixes those packages to be "sourceless" and sets their version to `1.0`.
=> Make the meta packages sourceless

bootstrap.d/sys-apps.yml, extrafiles/00-repository-main.conf, patches/xbps/0001-Managarm-specific-changes.patch, patches/xbps/0002-Add-the-Managarm-amd64-repository-and-remove-the-Voi.patch, patches/xbps/0003-Work-around-unimplemented-Managarm-features.patch
This PR updates the `xbps` recipe to no longer install an obsolete file, properly patches the Managarm specific info into the codebase and works around 2 issues in Managarm / mlibc pending their implementation.
This PR is blocked on managarm/mlibc#250, as it contains the buffering fixes and the `lchown` stub that `xbps` wants.
This PR is blocked on managarm/mlibc#288
Properly closes #71
=> Various updates to xbps

bootstrap.yml, patches/gcc/0001-Managarm-target.patch
This PR updates `gcc` and the toolchain to version 11.1.0.
This PR is blocked on managarm/managarm#369 and managarm/frigg#10
=> gcc: Update from version 10.3.0 to 11.1.0

.github/workflows/build-from-repos.yml, .github/workflows/container.yml
I also snuck in a commit to only upload rootfs from source repository. This prevents CI failing on forks.
=> Add workflow to build from xbps repos

bootstrap.yml, patches/llvm/0001-Managarm-specific-changes.patch, patches/llvm/0002-Add-managarm-target.patch, patches/protobuf/0001-Fix-various-stuff-for-managarm.patch, patches/protobuf/0002-managarm-add-protoc.pc.patch
This PR fixes various compilation errors under gcc 11. This PR contains fixes for `llvm` and `protobuf`.
Complements managarm/lewis#3
=> Fix various compilation errors under gcc 11

scripts/update-image.py
Fix lint errors according to `pyright`.
Possibly related to managarm/bootstrap-managarm#103.
=> scripts/update-image: fix lint errors

bootstrap.d/sys-apps.yml
Otherwise this corrupts the sysroot.
This wasn't actually a noticeable problem before we started using `xbps`.
=> rust: install packages to /usr/bin rather than /bin

bootstrap.d/dev-libs.yml, bootstrap.d/gnome-base.yml, bootstrap.d/net-dns.yml, bootstrap.d/net-libs.yml, bootstrap.d/x11-libs.yml, bootstrap.d/x11-misc.yml, bootstrap.d/x11-themes.yml, bootstrap.yml, docker/Dockerfile, patches/libgcrypt/0001-Add-Managarm-support.patch
This PR adds a bunch of new ports, all in preparation for upstreaming `gtk+3` and `WebKitGTK`. More ports are expected, but are in need of a cleanup. Furthermore, some post install scripts have been added and the Dockerfile has been updated to accommodate the new ports.
New ports:
- `libgcrypt`,
- `libunistring`,
- `libidn2`,
- `gnutls`,
- `gsettings-desktop-schemas`, includes a post install script to compile the schemas.
- `glib-networking`,
- `libpsl`,
- `libsoup`,
- `xcursor-themes`,
- `hicolor-icon-theme`.
New tools:
- `host-gobject-introspection`, only used for some aclocal files.
Updated ports:
- `shared-mime-info`, added a post install script to build the mime database,
- `gtk+2`, rename a file which conflicts with `gtk+3`, add a post install script to build a cache and depend on …
=> Add a bunch of new ports, working towards WebKitGTK

bootstrap.d/app-arch.yml, bootstrap.d/app-misc.yml, bootstrap.d/dev-libs.yml, bootstrap.d/media-fonts.yml, bootstrap.d/meta-pkgs.yml, bootstrap.yml
This PR adds metadata to several packages. The plan is to add this to all packages so `xbps` can display this to the end user.
Currently, the following packages have metadata applied to them:
- `managarm-kernel`,
- `managarm-system`,
- `mlibc-headers`,
- `mlibc`,
- `binutils`,
- `boost`,
- `core-files,`
- `base`,
- `base-devel`,
- `weston-desktop`,
- `zlib`,
- `ca-certificates`,
- `sl`,
- `dejavu`,
- `xorg-font-util`,
- `atk`,
- `d0-blind-id`,
- `fribidi`,
- `libtsm`,
- `kmscon`,
- `bzip2`,
- `gzip`,
- `libarchive`,
- `lz4`,
- `tar`,
- `xz-utils`,
- `zstd`.
As data sources for the metadata (descriptions, websites and licensing), I've aggregated information from https://packages.gentoo.org, https://linuxfromscratch.org (both LFS and BLFS) and the information provided by `aptitude show` on …
=> Add metadata to various packages

bootstrap.d/dev-lang.yml, bootstrap.d/dev-util.yml
This PR adds two new ports, `ninja` and `tcl`, both in various states of working. `ninja` requires `sigpending` to be useful and `tcl` is a user of `pthread_atfork` (see managarm/mlibc#298). Furthermore, ninja requires some mlibc work in `fopen`, a PR for that will be posted soon.
Part of #39 
Complemented (but not blocked!) by managarm/mlibc#299
=> Add ports of ninja and tcl

bootstrap.d/dev-libs.yml, bootstrap.d/x11-apps.yml, bootstrap.d/x11-themes.yml
The PR adding `xcursor-themes` was missing some dependencies in that recipe. It also fixed a missing tool and attempts to fix `host-gobject-introspection`.
=> Some small bugfixes for xcursor-themes and host-gobject-introspection

bootstrap.d/dev-lang.yml, bootstrap.d/meta-pkgs.yml, bootstrap.d/sys-libs.yml, bootstrap.yml
This PR is the managarm specific counterpart to managarm/mlibc#328. With this, we switch to `libxcrypt` as our crypt provider. I don't expect any significant breakage but we recompile `perl` and `python` for good measure to force them to link against the new libcrypt.
Blocked on managarm/mlibc#328
=> Switch to libxcrypt

bootstrap.d/app-emulation.yml, bootstrap.yml, patches/qemu/0001-configure-add-managarm-support.patch, patches/qemu/0002-qemu-thread-posix-patch-out-pthread_attr_setdetachst.patch
Some notes:
- The second patch should be removed once managarm/mlibc#311 is merged.
- Running qemu in a vm with more than one core may cause a kernel page fault.
=> app-emulation: add qemu port

bootstrap.d/net-print.yml, bootstrap.yml, extrafiles/group, extrafiles/passwd, patches/cups/0001-Add-Managarm-support.patch
This PR adds a port of `cups` and updates the `passwd` and `group` files to accommodate for this, by adding the `lpadmin` group and the `lp` user.
=> Add a cups port

bootstrap.d/x11-libs.yml
This PR adds 4 ports that I have had laying around for a while now, and improves our X stack a bit. It adds the following 4 ports:
- `xcb-util-image`;
- `xcb-util-keysyms`;
- `xcb-util-render-util`;
- `xcb-util-wm`.
=> Add several xcb-util ports

bootstrap.d/www-client.yml, bootstrap.yml
This PR adds a port of `links`, a basic webbrowser with a terminal and a GUI mode. As far as I tested, I found nothing that was broken and to my knowledge it needs no additions to mlibc or source code hacks. Launch it either as `links` for the terminal mode or `links -g` for the graphical mode. Escape to bring up the menu, which can be controlled with the arrow keys and contains a small but helpful section on how to control the browser.
=> Add a basic browser

bootstrap.d/x11-libs.yml
The Vinix team found several issues with our X libraries involving accidental linkage to libraries from the host. They fixed that problem for themselves and alerted us to it, I've backported their fix so that we're no longer affected by it as well.
=> X11 libraries fixes

bootstrap.d/media-libs.yml, patches/mesa/0001-Add-Managarm-support.patch
This PR updates `mesa` to version 21.3.5 and makes `mesa` use `libglvnd`. While not a hard dependency to use this at the moment, if we ever want to do `glamor` + `egl` + `wayland` things in `Xorg` (not `Xwayland`) we'll need to use this. Also a very initial and not really noteworthy step to nvidia drivers if that ever happens I guess.
Fixes what #159 was doing but properly.
Unblocks managarm/managarm#418
=> Update mesa to 21.3.5 and use libglvnd

bootstrap.d/dev-lang.yml, bootstrap.d/sys-libs.yml, extrafiles/config.toml, patches/rust-backtrace/0001-managarm-use-dl_iterate_phdr.patch, patches/rust-libc/0001-managarm-initial-port.patch, patches/rust-libc/0002-managarm-Add-missing-glue-for-memmap-num_cpus-and-us.patch, patches/rust-libc/0003-managarm-misc-additions-plus-dl_iterate_phdr.patch, patches/rust/0001-managarm-initial-port.patch, patches/rust/0002-managarm-fix-build-target-in-x.py-and-bootstrap.patch, patches/rust/0003-managarm-fixes-for-1.57.0.patch, scripts/cargo-inject-patches.py
Bump `host-rust` to 1.57. This involves some libc additions. We also enable backtraces via `dl_iterate_phdr` which requires us to patch the `backtrace` crate.
Supercedes https://github.com/managarm/bootstrap-managarm/pull/163.
=> rust: upgrade to 1.57.0

bootstrap.d/app-arch.yml, bootstrap.d/media-libs.yml, patches/giflib/0001-Don-t-build-the-documentation.patch, patches/unzip/unzip-6.0-consolidated_fixes-1.patch
This PR adds 4 new ports that are listed as required or recommended dependencies of `OpenJDK` according to BLFS. Even if not needed for that, 3 of these ports are general nice to haves.
The following new ports were added:
- `cpio`,
- `giflib`,
- `unzip`,
- `zip`.
=> A few new ports

bootstrap.d/dev-libs.yml, bootstrap.d/gnome-base.yml, bootstrap.d/net-libs.yml, bootstrap.d/x11-libs.yml, bootstrap.d/x11-misc.yml
This PR adds several missing post install hooks to glib and related packages. Fixing this allows for a better experience in Managarm.
=> Add various missing post install hooks

bootstrap.d/dev-lang.yml, bootstrap.d/media-libs.yml, bootstrap.d/sys-apps.yml, bootstrap.yml, patches/llvm/0001-Managarm-specific-changes.patch, patches/llvm/0002-Add-Managarm-target.patch, patches/rust/0001-managarm-initial-port.patch, patches/rust/0002-managarm-fix-build-target-in-x.py-and-bootstrap.patch, scripts/cross-llvm-config, scripts/meson-clang-aarch64-managarm.cross-file, scripts/meson-clang-x86_64-managarm.cross-file, scripts/meson-kernel-aarch64-managarm.cross-file, scripts/meson-kernel-riscv64-managarm.cross-file, scripts/meson-kernel-x86_64-managarm.cross-file
LLVM 14 has dropped, and that can mean only one thing, toolchain update time!
=> llvm: Update from version 13.0.1 to 14.0.1

bootstrap.d/media-libs.yml, patches/libtiff/0001-Don-t-fetch-new-versions-of-config.guess-and-config..patch
This PR splits off the `libwebp` port from #169, the `gstreamer` and `gst-plugins-base` ports from #152 and adds a port of `libtiff`, in preparation of `Qt6` and `GTK` to use them.
Blocked on managarm/mlibc#406
=> Add several libraries to be used by Qt and GTK

bootstrap.d/app-arch.yml, bootstrap.d/dev-libs.yml, bootstrap.d/dev-qt.yml, bootstrap.d/games-board.yml, bootstrap.yml, patches/qtbase6/0001-Add-Managarm-support.patch, patches/qtdeclarative6/0001-Add-Managarm-support.patch
- `double-conversion`;
- `brotli`;
- `pcre2`;
- `qtbase`;
- `qtsvg`;
- `qtlanguageserver`;
- `qtshadertools`;
- `qtimageformats`;
- `qtdeclarative`;
- `qtmultimedia`;
- `libremines`.
Blocked on managarm/mlibc#406
Blocked on #176
=> Add an initial port of a subset of Qt6

bootstrap.d/x11-apps.yml
Running `xclock -help` without `util-linux-libs` installed complains about missing `libuuid.so.1`, which is solved this way.
=> xclock: add missing dependency on util-linux-libs

bootstrap.d/x11-apps.yml
Reverts managarm/bootstrap-managarm#183 since xbbs was already able to build the package correctly and `util-linux-libs` already shows up as a dependency.
=> Revert "xclock: add missing dependency on util-linux-libs"

bootstrap.yml, scripts/meson-clang-aarch64-managarm.cross-file, scripts/meson-clang-x86_64-managarm.cross-file, scripts/meson-kernel-x86_64-managarm.cross-file, scripts/meson-x86_64-managarm.cross-file
As discussed on Discord. This allows cxxshim and frigg to be found via `pkg-config` rather than needing to do `ln` hacks.
Some things may break if they incorrectly use frigg without declaring it as a dependency, see e.g https://github.com/managarm/managarm/pull/453.
=> bootstrap.yml: install cxxshim and frigg headers to /usr/share

bootstrap.d/sys-libs.yml, bootstrap.d/x11-terms.yml, bootstrap.yml, extrafiles/config.toml, patches/rust-calloop/0001-managarm-initial-port.patch, patches/rust-glutin/0001-managarm-initial-port.patch, patches/rust-libc/0001-managarm-initial-port.patch, patches/rust-libc/0002-managarm-Add-missing-glue-for-memmap-num_cpus-and-us.patch, patches/rust-libc/0003-managarm-alacritty-updates.patch, patches/rust-libloading/0001-managarm-initial-port.patch, patches/rust-mio-0.6/0001-managarm-initial-port.patch, patches/rust-mio-0.8/0001-managarm-initial-port.patch, patches/rust-nix/0001-managarm-initial-port.patch, patches/rust-shared-library/0001-managarm-initial-port.patch, patches/rust-winit/0001-managarm-initial-port.patch, scripts/cargo-inject-patches.py
Ports the required libraries for alacritty, including some bits of nix and mio.
Blocked on a number of PRs (but ready to go once they're merged):
=> rust: port alacritty

docker/Dockerfile
Add `yodl` to the Docker image, as for the first build of `zsh` in #187 not to fail.
=> docker: add yodl

scripts/managarm-lsp-launcher.sh
Blocked on https://github.com/managarm/managarm/issues/427 and cbuildrt and xbstrap releases.
EDIT: we should add a way to give extra packages to `xbstrap lsp` before releasing and merging.
EDIT2: https://github.com/managarm/xbstrap/pull/64
=> scripts: add managarm-lsp-launcher.sh

bootstrap.d/dev-lang.yml, bootstrap.d/x11-terms.yml, patches/rust-libc/0003-managarm-alacritty-updates.patch, scripts/cargo-inject-patches.py
Bump cargo version to match rustc. This should fix alacritty on CI.
=> rust: bump cargo version to 1.60.0

bootstrap.d/app-misc.yml, bootstrap.d/dev-libs.yml, patches/nss/0001-Add-a-missing-include.patch, patches/nss/0002-NSS-Standalone-patch.patch
This PR updates ca-certs to the version from NSS 3.77, and adds ports for NSPR and NSS.
Blocked on managarm/mlibc#415
=> Add NSPR and NSS ports

scripts/limine.cfg, scripts/update-image.py
The stivale boot protocols are deprecated and due to be removed in Limine 4.0.
We could move to the Limine boot protocol but I don't think there is a need to do so due to eir already supporting multiboot2 just fine (which is not deprecated).
=> Drop stivale2 boot protocol in favour of multiboot2

bootstrap.d/app-arch.yml, bootstrap.d/dev-lang.yml, bootstrap.d/dev-libs.yml, bootstrap.d/net-misc.yml, bootstrap.d/sys-apps.yml, bootstrap.d/sys-libs.yml, bootstrap.yml
The following ports received updates:
- `zlib`, from version 1.2.11 to 1.2.12;
- `zstd`, from version 1.5.0 to 1.5.2;
- `file`, from version 5.41 to 5.42;
- `tcl`, from version 8.6.11 to 8.6.12;
- `iana-etc`, from version 20211124 to 20220610;
- `tzdata`, from version 2021e to 2022b;
- `gmp`, from version 6.2.0 to 6.2.1;
- `gdbm`, from version 1.22 to 1.23;
- `libexpat`, from version 2.4.1 to 2.4.8;
- `less`, from version 563 to 590;
- `coreutils`, from version 9.0 to 9.1;
- `findutils`, from version 4.8.0 to 4.9.0;
- `gzip`, from version 1.11 to 1.12.
This is not everything but I'm breaking it up into smaller parts due to vacation.
=> Some small updates

bootstrap.d/dev-libs.yml, bootstrap.d/media-libs.yml, bootstrap.d/sys-apps.yml, bootstrap.d/sys-libs.yml, bootstrap.d/www-client.yml, bootstrap.d/x11-libs.yml, docker/Dockerfile, patches/fontconfig/0001-Add-Managarm-support.patch, patches/libiconv/0001-Remove-calls-to-versioned-binaries.patch, patches/libtiff/0001-Don-t-fetch-new-versions-of-config.guess-and-config..patch
The following ports received updates:
- `libiconv`, from version 1.16 to 1.17;
- `libjpeg-turbo`, from version 2.1.2 to 2.1.4;
- `libpipeline`, from version 1.5.4 to 1.5.6;
- `libtasn`, from version 4.17.0 to 4.18.0;
- `libtiff`, from version 4.3.0 to 4.4.0;
- `libunistring`, from version 0.9.10 to 1.0;
- `libwebp`, from version 1.2.2 to 1.2.4;
- `libX11`, from version 1.7.3 to 1.8.1;
- `libxcb`, from version 1.14 to 1.15;
- `libxcrypt`, from version 4.4.26 to 4.4.28;
- `libXcursor`, from version 1.2.0 to 1.2.1;
- `libxkbcommon`, from version 1.3.1 to 1.4.1;
- `libxml`, from version 2.9.12 to 2.10.0;
- `links`, from version 2.25 to 2.27;
- `nettle`, from version 3.7.3 to 3.8.1.
The dockerfile got updated to install `python3-xcbgen` which is needed for `libxcb` to generate some files …
=> Another batch of updates

bootstrap.d/dev-qt.yml, bootstrap.d/games-board.yml, patches/libremines/0001-Disable-sound-as-we-don-t-support-sound.patch, patches/qtbase6/0001-Add-Managarm-support.patch
This PR updates the following packages:
- `host-qt6`, from version 6.3.0 to version 6.4.0;
- `qtbase6`, from version 6.3.0 to version 6.4.0;
- `qtimageformats6`, from version 6.3.0 to version 6.4.0;
- `qtlanguageserver6`, from version 6.3.0 to version 6.4.0;
- `qtshadertools6`, from version 6.3.0 to version 6.4.0;
- `qtsvg6`, from version 6.3.0 to version 6.4.0;
- `qtdeclarative6`, from version 6.3.0 to version 6.4.0;
- `qtmultimedia6`, from version 6.3.0 to version 6.4.0;
- `libremines` got a patch to disable sound.
Furthermore, `qtwayland6` got added as a port, allowing us to run Qt6 based GUI applications without X11/XWayland running.
=> Qt stack updates

bootstrap.d/app-accessibility.yml, bootstrap.d/dev-libs.yml, bootstrap.d/sys-apps.yml, bootstrap.d/x11-libs.yml, bootstrap.yml, patches/dbus/0001-Disable-the-use-of-getresuid-as-we-don-t-implement-t.patch, patches/gtk+-3/0001-Initial-Managarm-support.patch
This PR splits off the `gtk3` part from #152. Several issues still remain, including `dbus` not working properly and `gtk3` missing `pwrite()`, potentially among other things.
- `libxslt`,
- `dbus`,
- `at-spi2-core`,
- `at-spi2-atk`,
- `gtk+-3`.
Blocked on #168 and a draft pending the things I mentioned above.
Blocked on #176
=> Add a port of GTK3 and related dependencies

bootstrap.d/app-misc.yml
This PR adds a `cmatrix` port, enables `sl` for AArch64 and fixes some metadata ordering.
=> Add a cmatrix port

bootstrap.d/sys-kernel.yml, bootstrap.yml
Hard blocked on managarm/mlibc#784.
=> mlibc: switch to using external linux kernel headers

ci/pipeline.yml
Fixes broken xbbs after #221, or so we hope.
=> ci: Fix the system-toolchain job after the kernel headers

bootstrap.d/media-libs.yml, bootstrap.yml, patches/llvm/0001-Managarm-specific-changes.patch, patches/llvm/0002-Add-Managarm-target.patch, patches/mesa/0001-Add-Managarm-support.patch, patches/mesa/0002-Enable-DMABUF-for-managarm.patch, patches/mesa/0003-Disable-futex-for-managarm.patch, scripts/cross-llvm-config
Also includes a bump for `mesa`. This LLVM version is needed for the `.clang-format` file I'm about to PR in.
=> llvm: Update from version 14.0.5 to 16.0.6

bootstrap.d/games-misc.yml
Apparently, the checksum for the archive changed despite not receiving a version bump. Checking with gpg against the authors public key is fine, though, so we need to update our blake2b hash.
=> gtklife: update checksum, use https

bootstrap.d/x11-libs.yml, patches/libdrm/0001-Managarm-specific-changes.patch, patches/libdrm/0002-Add-more-managarm-specific-changes.patch, patches/libdrm/0003-Even-more-managarm-specific-changes.patch
This allows for successfully running `drmGetDevice` et al. when the necessary sysfs changes land in managarm. Without them, the function will still fail with an error, same as before.
=> libdrm: rebase patches and enable linux codepaths for managarm

bootstrap.d/dev-libs.yml, bootstrap.d/sys-apps.yml
This PR adds a port of the following packages:
- `libusb`;
- `usbutils`.
`usbutils` doesn't display anything yet because we're missing the sysfs interfaces for it, but @no92 wanted to work on that after his vacation.
=> Add two USB related ports

bootstrap.d/app-accessibility.yml, bootstrap.d/app-arch.yml, bootstrap.d/app-crypt.yml, bootstrap.d/app-editors.yml, bootstrap.d/dev-libs.yml, bootstrap.d/media-libs.yml, bootstrap.d/meta-pkgs.yml, bootstrap.d/sys-apps.yml, bootstrap.d/x11-libs.yml, bootstrap.yml, extrafiles/nanorc, extrafiles/root-nanorc, patches/automake-v1.16/0001-Add-Managarm-support.patch, patches/p11-kit/0001-Fill-in-the-distribution-specific-anchor-hook-for-Ma.patch, patches/p11-kit/0002-Work-around-an-issue-with-the-build-system.patch, patches/p11-kit/0003-Make-Managarm-use-the-GNU-compatible-strerror_r.patch
This PR updates a few ports and adds `iproute2` and `man-pages-posix` to the base image.
List of updated ports:
- `at-spi2-core`;
- `gtk3`;
- `libarchive`;
- `lz4`;
- `zstd`;
- `xz-utils`;
- `tar`;
- `libtasn`;
- `p11-kit`;
- `nano`;
- `fribidi`;
- `icu`;
- `libexpat`;
- `libevdev`;
- `libpipeline`;
- `libunistring`;
- `double-conversion`;
- `libjpeg-turbo`;
- `libwebp`;
- `libtiff`;
- `gawk`;
- `grep`;
- `file`.
Furthermore, `host-automake-v1.16` has been added as a tool.
=> Update a few packages

bootstrap.d/net-irc.yml, bootstrap.yml, patches/hexchat/0001-Add-missing-includes.patch
This PR adds a port of `hexchat`, the `gtk+-2` based IRC client. After way too much time, I finally tried to repair this long forgotten beauty that was left to rot, and after more than one year of sitting here waiting I have finally finished restoring it. It remains blocked on a couple of error handling PRs listed below but once all of those are merged I see no blockers to finally merging this `hexchat` PR.
=> Add a port of hexchat

bootstrap.d/app-admin.yml
Mainly useful for `mpstat`, which (combined with my WIP scheduler PR) can read out the current CPU and boot-time average CPU usage from `/proc/stat`.
=> sysstat: add port

bootstrap.d/dev-qt.yml, bootstrap.d/sys-apps.yml, bootstrap.d/x11-libs.yml
This PR fixes a Werror warning in `pango` by updating it and adds a missing dependency on `zlib` for `pciutils` and on `xcb-util-cursor` for `qtbase6`.
=> Small fixes

bootstrap.d/gui-apps.yml, patches/havoc/0001-Change-some-config-values-to-sane-defaults.patch
This PR adds a port of `havoc`, a minimalistic terminal emulator for weston.
Blocked on managarm/mlibc#398
=> havoc: Add port

bootstrap.d/games-misc.yml
Can't leave AArch64 without nyancat can we? Untested but I see no issues with this build.
=> nyancat: Add missing metadata and build on AArch64

bootstrap.d/gui-libs.yml, bootstrap.d/net-libs.yml, patches/webkitgtk/0001-Initial-Managarm-support.patch
This PR adds a port of `webkitgtk`. This PR remains a draft for the foreseeable future and only serves to help others debug various issues in `webkitgtk`.
- `libwpe` (needed for newer versions);
- `wpebackend-fdo` (needed for newer versions);
- `webkitgtk`.
Blocked on #169 
Blocked on #176 
Blocked on managarm/managarm#525
Blocked on managarm/managarm#526
=> Port webkitgtk

scripts/grub.cfg, scripts/limine.cfg, scripts/update-image.py
Update the disk layout to accomodate Limine 6 dropping support for Ext2/3/4.
This will require everyone to create new disk images since the ESP needs to be
larger now. `update-image.py` will issue an
Depends on https://github.com/qookei/image_create/pull/1 for creating images
with the new partition table layout.
=> Limine 6 fixes

bootstrap.d/dev-libs.yml, bootstrap.yml
Enable decimal float support on AArch64 libgcc. This patch should probably be upstreamed to gcc at some point too.
=> libgcc: Enable decimal float support for AArch64

bootstrap.d/app-shells.yml, bootstrap.yml, docker/Dockerfile
This adds a zsh port that seems to work for simple command-line use. Building this requires `yodl` being installed in the rootfs, i.e. chroot into the rootfs and run `apt install yodl`. Including this as a host-tool would introduce 2 host-tools with ridiculous build systems.
=> zsh: add port

bootstrap.d/app-crypt.yml, bootstrap.d/app-text.yml, bootstrap.d/dev-lang.yml, bootstrap.d/dev-libs.yml, bootstrap.d/gnome-extra.yml, bootstrap.d/gui-libs.yml, bootstrap.d/media-libs.yml, bootstrap.d/net-dns.yml, bootstrap.d/net-libs.yml, bootstrap.d/sys-libs.yml, bootstrap.d/x11-libs.yml, bootstrap.yml, docker/Dockerfile, patches/appstream/0001-Add-Managarm-support.patch, patches/gtk4/0001-Add-Managarm-support.patch, scripts/cross-valac, scripts/cross-vapigen, scripts/meson-x86_64-managarm.cross-file, scripts/meson.native-file
This PR adds a port of `gnome-calculator` and enables introspection on large parts of the stack. It also comes with `host-vala`, so that we can process vala items. Along the way, a free fix to `readline` and `zlib` were added.
=> Port gnome-calculator

bootstrap.yml
This is necessary to update the xbbs-built version, as it continues to rely on protobuf, which we recently removed.
=> host-managarm-tools: bump revision

bootstrap.d/dev-libs.yml, bootstrap.d/meta-pkgs.yml, bootstrap.d/sys-apps.yml, bootstrap.d/sys-libs.yml, bootstrap.d/sys-process.yml, patches/elfutils/0001-Add-Managarm-support.patch, patches/procps/0001-Add-Managarm-support.patch
Add `procps` and mark `htop` and `procps` as buildable for AArch64. Also add them to the `base` package. Tell `coreutils` to not install `uptime`, `procps` provides that.
Also adds `argp-standalone`, `fts-standalone`, `obstack-standalone` and `elfutils` as ports.
Depends on managarm/mlibc#941
Depends on managarm/mlibc#942
Depends on managarm/mlibc#943
=> procps: Add port

bootstrap.d/x11-libs.yml, bootstrap.yml
This package is derived from the libdrm source, and only serves to extract the drm headers into a package. mlibc depends on having libdrm headers present for building managarm sysdeps, and libdrm does not support extracting the headers. This commit adds the libdrm-headers package, which copies out the headers and supplies a `meson.build` to allow for other meson-based projects (like mlibc) to use the headers as a subproject. This avoids sandbox violations and hardcoding paths between packages.
=> libdrm-headers: Add package

bootstrap.d/games-misc.yml
This PR changes three openttd-related packages to use the new `managarm-mirrors` repository as a source for the package files, instead of my personal mirror. The files are the exact same; as the hash has not changed, no rebuild or revision bump should be needed.
=> openttd-open{gfx, msx, sfx}: change to git mirror

.github/workflows/container.yml
This link is needed eg. by openjdk's build process.
=> github: Link /dev/fd to /proc/self/fd in rootfs

bootstrap.d/dev-util.yml
iana provides an amalgamated tzcode and tzdata package, which is useful since xbstrap cant create a single package from multiple sources. This was added to aid in cross compiling postgresql - which requires zic from tzcode as well as tzdata.
=> ports/util: add combined tzdata and tzcode package

bootstrap.d/app-emulation.yml
We can do this due to host-qemu being containerless and linking against a lot of system libraries, making it highly unlikely to be portable between systems anyways.
=> host-qemu: enable `-march=native`

bootstrap.d/x11-libs.yml
The git submodules referenced by these packages changed locations, switch to latest commits and bump revisions to fix CI.
=> x11-libs: Bump xcb-util{,-keysyms,-render-util} to fix CI

bootstrap.d/x11-libs.yml
Missed these two packages in 53b81dceb82a90654bcdad427d82f2bbf4755c21.
=> x11-libs: Bump xcb-util-{image,cursor} to fix CI

.github/workflows/build-from-repos.yml, .github/workflows/sanity-check.yml, bootstrap.d/app-accessibility.y4.yml, bootstrap.d/app-arch.y4.yml, bootstrap.d/app-crypt.y4.yml, bootstrap.d/app-misc.y4.yml, bootstrap.d/dev-lang.y4.yml, bootstrap.d/dev-libs.y4.yml, bootstrap.d/dev-util.y4.yml, bootstrap.d/games-emulation.y4.yml, bootstrap.d/gnome-base.y4.yml, bootstrap.d/gui-libs.y4.yml, bootstrap.d/managarm-libs.y4.yml, bootstrap.d/managarm-system.y4.yml, bootstrap.d/media-libs.y4.yml, bootstrap.d/net-libs.y4.yml, bootstrap.d/sys-apps.y4.yml, bootstrap.d/sys-boot.y4.yml, bootstrap.d/sys-process.y4.yml, bootstrap.d/tasks.y4.yml, bootstrap.d/x11-apps.y4.yml, bootstrap.d/x11-libs.y4.yml, scripts/update-image.py, y4.d/managarm.yaml
Mainly just disabling gobject-introspection on AArch64 via y4.
=> Fix AArch64 build

bootstrap.d/sys-boot.y4.yml, bootstrap.d/tasks.y4.yml, bootstrap.yml
Also make host-limine not a containerless tool and build it using host-llvm-toolchain.
The make-image task is still containerless because it actually mounts the disk image (either via loopback or guestfs), but ideally it shouldn't be, because it invokes 'strip' from cross-binutils, which just happens to work outside the container.
Depends on https://github.com/qookei/image_create/pull/2.
=> bootstrap: Run {initialize-empty,remake}-image tasks in the container

bootstrap.d/managarm-build.y4.yml
This ensures that we use the newest `config.sub` and `config.guess`. Without this patch, `riscv64-managarm` is not recognized by automake.
=> automake: Take config.sub from gnuconfig

bootstrap.d/tasks.y4.yml, scripts/vm-util.py
This allows vm-util.py to verify the output of qemu (such that we do not have to rely on the less sophisticated `test-image.py` anymore).
=> vm-util: Integrate --expect and --expect-not

bootstrap.d/app-accessibility.y4.yml, bootstrap.d/app-editors.y4.yml, bootstrap.d/app-shells.y4.yml, bootstrap.d/dev-db.y4.yml, bootstrap.d/dev-lang.y4.yml, bootstrap.d/dev-libs.y4.yml, bootstrap.d/dev-qt.y4.yml, bootstrap.d/dev-util.y4.yml
This PR adds metadata to a bunch of packages. It also upgrades 2 packages that were accidentally forgotten in the Qt6 stack.
=> Add metadata to a bunch of packages

bootstrap.d/sys-apps.y4.yml, bootstrap.d/sys-libs.y4.yml, patches/nvme-cli/0001-Add-missing-include.patch
This PR adds a port of the following packages:
- `libnvme`;
- `nvme-cli`.
Blocked on managarm/mlibc#1206
=> nvme-cli: Add port

bootstrap.d/app-misc.y4.yml, bootstrap.d/x11-apps.y4.yml
These were useful for evdev testing, specifically for multitouch.
=> Add `evtest` and `mtview` ports

scripts/vm-util.py
QEMU emulates UMIP regardless of whether or not it is supported. It does that by trapping every table access, including ltr, which we do on task switch when the I/O permission bitmap changes. This is quite costly in performance, so we disable UMIP if the host does not support it.
=> vm-util: Disable UMIP if it is not supported on the host

bootstrap.d/media-libs.y4.yml
Pass `-mno-relax` on RISC-V to work around a build failure (toolchain issue?).
=> libpng: Workaround RISC-V build failure

bootstrap.d/sys-apps.y4.yml, bootstrap.d/sys-devel.y4.yml
This PR updates sed and m4 to fix gnulib related breakages after strerror_r was changed to provide both signatures as needed.
=> Gnulib updates

bootstrap.d/dev-libs.y4.yml, bootstrap.d/gui-libs.y4.yml, bootstrap.d/kde-frameworks.y4.yml, bootstrap.d/managarm-system.y4.yml, bootstrap.d/media-libs.y4.yml, bootstrap.d/net-misc.y4.yml, bootstrap.d/sys-apps.y4.yml, bootstrap.d/x11-apps.y4.yml, bootstrap.d/x11-base.y4.yml, patches/systemd/0001-Add-managarm-support.patch, patches/systemd/0002-Add-support-for-systemd-boot-for-Managarm.patch, patches/systemd/0003-add-fallback-parse_printf_format-implementation.patch, scripts/limine.conf
This PR adds the necessary patchwork to allow systemd to boot a Managarm system into Weston.
Additional patches enabling weston and kmscon will follow later.
For now, if one has it locally, one can specify `systemd` on the kernel commandline to force stage1 to exec into systemd, otherwise the stage2 fallback will be used.
Part of the systemd on Managarm project.
=> Systemd boot

bootstrap.d/sys-apps.y4.yml
This PR enables systemd support on dbus
Part of the systemd on Managarm project.
=> dbus: Enable systemd support

bootstrap.d/app-misc.y4.yml, bootstrap.d/dev-libs.y4.yml, bootstrap.d/managarm-base.y4.yml, bootstrap.d/meta-pkgs.y4.yml, bootstrap.d/net-misc.y4.yml, bootstrap.d/sys-apps.y4.yml, patches/dbus/0001-Disable-the-use-of-getresuid-as-we-don-t-implement-t.patch, patches/dbus/0002-Add-Managarm-support-and-remove-unimplemented-items-.patch, patches/dhcpcd/0001-Add-managarm-support.patch, patches/dhcpcd/0002-Add-systemd-unit-file.patch, patches/fastfetch/0001-Add-Managarm-support.patch, patches/kmscon/0001-Fix-a-few-things-to-make-kmscon-compile-for-managarm.patch, patches/kmscon/0002-Disable-system-locale-querying-via-dbus.patch, patches/shadow/0001-Add-Managarm-support.patch, patches/systemd/0001-Add-managarm-support.patch, patches/systemd/0002-Add-support-for-systemd-boot-for-Managarm.patch, patches/systemd/0003-add-fallback-parse_printf_format-implementation.patch, patches/weston/0002-Add-systemd-unit-files.patch, scripts/limine.conf
This PR fixes `dbus` to not be broken when launched over `systemd`, fixes a broken installation path for `weston`, removes now unneeded patches for `systemd` and enables utmp and logind, removes an unneeded symlink made by `core-files`, enables `systemd` support in `kmscon` and updates the limine.conf to reflect that. It also updates `fastfetch` to enable checking for which systemd version we run and adds a systemd unit to `dhcpcd`. Finally, the `base` metapackage was updated to include `dbus` by default.
Blocked on managarm/managarm#888
=> More systemd fixes and enablement for kmscon

bootstrap.d/x11-apps.y4.yml
With gitlab.freedesktop.org down, and the fact that `kmscube` checks out a commit and is therefore not catched by the mirroring task, let's switch to the debian mirror, at least for now.
=> kmscube: Switch to debian mirror

bootstrap.d/net-misc.y4.yml
Depends on minor mlibc changes to stub some `getsockopt` calls, hence drafting for now.
=> iperf3: add port

bootstrap.d/dev-lang.y4.yml
Changes made in #489 mistakenly made xbstrap build only clippy as part of host-rust, this PR fixes that.
=> host-rust: Fix rustc not being built

scripts/limine.conf
Update the Physical Hardware entries in the limine.conf file to log to serial using the userspace serial logging infrastructure, along with logging thor early boot logs to COM1.
Also use the systemd.target boot argument.
=> scripts: update limine config
